version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: iambatman
      MYSQL_USER: root
      MYSQL_PASS: iambatman 
      MYSQL_DATABASE: crud
      MYSQL_HOST: littlepeepee.cbxvbo02ioar.us-east-1.rds.amazonaws.com
    ports:
      - "3306:3306" 
  app:
    build: .
    command: bundle exec rails s
    volumes:
      - .:/crud-app
    ports:
      - "3001:3000"
    links:
      - db:sql_srv
    depends_on:
      - db
